name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        php-versions: ["8.3", "8.4"]
        drupal-version: ["10.6", "11.3"] 

    name: PHP ${{ matrix.php-versions }} | Drupal ${{ matrix.drupal-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create docker network
        run: docker network create ci-default

      - name: PHPUnit tests
        run: |
          docker run \
            --rm \
            --name drupal \
            --hostname drupal \
            --volume $(pwd):/var/www/drupal/web/modules/contrib/$ENABLE_MODULES:ro \
            --env ENABLE_MODULES \
            --network ci-default \
           ghcr.io/islandora/ci:${{ matrix.drupal-version }}-php${{ matrix.php-versions }}
        env:
          ENABLE_MODULES: termwithuri_condition